export const authorConstants = {
    CREATE_REQUEST: 'AUTHOR_CREATE_REQUEST',
    CREATE_SUCCESS: 'AUTHOR_CREATE_SUCCESS',
    CREATE_FAILURE: 'AUTHOR_CREATE_FAILURE',
    GETALL_REQUEST: 'AUTHOR_GETALL_REQUEST',
    GETALL_SUCCESS: 'AUTHOR_GETALL_SUCCESS',
    GETALL_FAILURE: 'AUTHOR_GETALL_FAILURE',
    DELETE_REQUEST: 'AUTHOR_DELETE_REQUEST',
    DELETE_SUCCESS: 'AUTHOR_DELETE_SUCCESS',
    DELETE_FAILURE: 'AUTHOR_DELETE_FAILURE'
}