export const bookConstants = {
    CREATE_REQUEST: 'BOOK_CREATE_REQUEST',
    CREATE_SUCCESS: 'BOOK_CREATE_SUCCESS',
    CREATE_FAILURE: 'BOOK_CREATE_FAILURE',
    GETALL_REQUEST: 'BOOK_GETALL_REQUEST',
    GETALL_SUCCESS: 'BOOK_GETALL_SUCCESS',
    GETALL_FAILURE: 'BOOK_GETALL_FAILURE'
}